baseURL: https://blog.pseudot.org
languageCode: en-us
title: pseudoblog
theme: mini

defaultContentLanguage: en

hasCJKLanguage: true
permalinks:
  posts: /posts/:title/

paginate: 5


# Hugo Configure Markup
# More info: https://gohugo.io/getting-started/configuration-markup#
markup:
  highlight:
    guessSyntax: true
    style: emacs
  tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 2
  # needed to render raw HTML (e.g. <sub>, <sup>, <kbd>, <mark>)
  goldmark:
    renderer:
      unsafe: true

# Social links in footer, support github,twitter,stackoverflow,facebook
social:
  # e.g.
  #github: your-github-link
  #twitter: your-github-link
  #stackoverflow: your-github-link
  # facebook: your-facebook-link


# Site parameters
params:
  # Site Author
  author: Andy
  # Site Motto
  motto: Tout ce qui passe dans ma tête
  # Site Description, used in HTML meat
  description: Main page


  ###########################################
  # Optional Configuration
  ###########################################

  # To enable RSS, you could set `enableRSS: true`, default is `true`
  enableRSS: false
  # To enable table of content, you could set `showToc: true`, default is `false`
  showToc: true
  # To hidden powerBy message in the page footer, you could set: `showPowerBy: false`, default is `true`
  showPowerBy: false
  # To enable math typesetting , you could set `math: true`, default is `false`
  math: false
  # To hidden post summary in home page, you could set `hiddenPostSummaryInHomePage: true`, default is `false`
  hiddenPostSummaryInHomePage: false
  # Website copy write, default: '© Copyright 2021 ❤️ {params.author}'
  copyright: '' 

  # Extra links in navigation
  links:
     - name: main
       url: https://pseudot.org/
     - name: books
       url: https://books.pseudot.org/
     - name: photography
       url: https://photos.pseudot.org/
     - name: programming
       url: https://programming.pseudot.org/
     - name: music
       url: https://music.pseudot.org/
     - name: uc
       url: https://uc.pseudot.org/

  # You can put your custom css and js to `static` directory, or use remote css and js files which start with `http://` or `https://`
  customCSS:
    ## e.g.
    # - css/custom.css # local css in `static/css/custom.css`
    # - https://example.com/custom.css # remote css
  customJS:
    ## e.g.
    # - js/custom.js # local js in `static/js/custom.js`
    # - https://example.com/custom.js # remote js
