baseurl = "https://programming.pseudot.org"
RSSLink = "https://programming.pseudot.org/index.xml"
title = "Pseudoprogramming"
languageCode = "en-us"
paginate = "8"
theme = "binario"

  name = "Andrei"
  bio = "Computer science enthusiast!"

[Params]
  enableRSS = true
  description = "Pseudoprogramming blog"
  opengraph = true # Enable OpenGraph if true
  schema = true # Enable Schema
  columns = 2 # Set the number of cards columns. Possible values: 2, 2, 3
  mainSections = ["posts"] # Set main page sections
  dateFormat = "02 January 2006" # Change the format of dates
  colorTheme = "dark-red" # dark-green, dark-blue, dark-red, dark-violet
  mainMenuAlignment = "right" # Align main menu (desktop version) to the right side
  authorbox = true # Show authorbox at bottom of single pages if true
  related = true # Enable Related content for single pages
  relatedMax = 5 # Set the maximum number of elements that can be displayed in related block. Optional
  mathjax = true # Enable MathJax for all site pages
  mathjaxPath = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js" # Specify MathJax path. Optional
  mathjaxConfig = "TeX-AMS-MML_HTMLorMML" # Specify MathJax config. Optional
  hideNoPostsWarning = false # Don't show no posts empty state warning in main page, if true

[Params.Entry]
  meta = ["date", "categories", "tags"] # Enable meta fields in given order
  toc = true # Enable Table of Contents
  tocOpen = true # Open Table of Contents block. Optional

[Params.Featured]
  previewOnly = false # Show only preview featured image

[Params.Social]
  email = "andreivavilov@pseudot.org"
  facebook = "username"
  twitter = "username"
  telegram = "username"
  instagram = "username"
  pinterest = "username"
  vk = "username"
  linkedin = "username"
  github = "username"
  gitlab = "username"
  stackoverflow = "numberid"
  mastodon = "https://some.instance/@username"
  medium = "username"

[Params.Share] # Entry Share block
  facebook = false
  twitter = false
  reddit = false
  telegram = false
  linkedin = false
  vk = false
  pocket = false
  pinterest = false

[Params.Manifest]
  name = "Pseudoprogramming blog"
  shortName = "Pseudoprogramming blog"
  display = "browser"
  startUrl = "/"
  backgroundColor = "#2a2a2a"
  themeColor = "#1b1b1b"
  description = "Pseudoprogramming blog"
  orientation = "portrait"
  scope = "/"


[[Params.links]]
  name = "main"
  url = "https://pseudot.org/"
[[Params.links]]
  name = "blog"
  url = "https://blog.pseudot.org/"
[[Params.links]]
  name = "books"
  url = "https://books.pseudot.org/"
[[Params.links]]
  name = "photography"
  url = "https://photos.pseudot.org/"
[[Params.links]]
  name = "uc"
  url = "https://uc.pseudot.org/"
[[Params.links]]
  name = "about"
  url = "https://pseudot.org/about"

[outputFormats]
  [outputFormats.MANIFEST]
    mediaType = "application/json"
    baseName = "manifest"
    isPlainText = true
    notAlternative = true

[outputs]
  home = ["HTML", "RSS", "MANIFEST"]
